# Generated by Django 3.1.6 on 2021-05-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AArearoi',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('areaid', models.IntegerField(db_column='AreaID')),
                ('anatomyid', models.CharField(db_column='AnatomyID', max_length=45)),
            ],
            options={
                'db_table': 'a_arearoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ALabeledimage',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('imageid', models.CharField(db_column='ImageID', max_length=45)),
                ('areaid', models.IntegerField(db_column='AreaID')),
                ('path', models.TextField(blank=True, db_column='Path', null=True)),
                ('pathtype', models.CharField(db_column='PathType', max_length=20)),
                ('userid', models.CharField(db_column='UserID', max_length=45)),
                ('usertype', models.CharField(db_column='UserType', max_length=10)),
                ('userid_check_1', models.CharField(blank=True, db_column='UserID_Check_1', max_length=45, null=True)),
                ('userid_check_2', models.CharField(blank=True, db_column='UserID_Check_2', max_length=45, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('patientid', models.CharField(db_column='PatientID', max_length=45)),
            ],
            options={
                'db_table': 'a_labeledimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anatomydict',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('anatomyname', models.CharField(db_column='AnatomyName', max_length=45)),
                ('anatomyid', models.CharField(db_column='AnatomyID', max_length=45)),
            ],
            options={
                'db_table': 'anatomydict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DArearoi',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('areaid', models.IntegerField(db_column='AreaID')),
                ('diseaseid', models.CharField(db_column='DiseaseID', max_length=10)),
            ],
            options={
                'db_table': 'd_arearoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diseasedict',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('diseasename', models.CharField(db_column='DiseaseName', max_length=45)),
                ('diseaseid', models.CharField(db_column='DiseaseID', max_length=45)),
            ],
            options={
                'db_table': 'diseasedict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DLabeledimage',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('imageid', models.CharField(db_column='ImageID', max_length=45)),
                ('areaid', models.IntegerField(db_column='AreaID')),
                ('path', models.TextField(blank=True, db_column='Path', null=True)),
                ('pathtype', models.CharField(db_column='PathType', max_length=20)),
                ('userid', models.CharField(db_column='UserID', max_length=45)),
                ('usertype', models.CharField(db_column='UserType', max_length=10)),
                ('userid_check_1', models.CharField(blank=True, db_column='UserID_Check_1', max_length=45, null=True)),
                ('userid_check_2', models.CharField(blank=True, db_column='UserID_Check_2', max_length=45, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('patientid', models.CharField(blank=True, db_column='PatientID', max_length=45, null=True)),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=45)),
            ],
            options={
                'db_table': 'd_labeledimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalRecord',
            fields=[
                ('instituteid', models.CharField(db_column='InstituteID', max_length=11, primary_key=True, serialize=False)),
                ('institutename', models.CharField(db_column='InstituteName', max_length=45)),
            ],
            options={
                'db_table': 'hospital_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagepath',
            fields=[
                ('checknumber', models.CharField(db_column='CheckNumber', max_length=20)),
                ('patientid', models.CharField(db_column='PatientID', max_length=45)),
                ('imageid', models.CharField(db_column='ImageID', max_length=45, primary_key=True, serialize=False)),
                ('imgpath', models.CharField(db_column='ImgPath', max_length=255)),
            ],
            options={
                'db_table': 'imagepath',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patientbasicinfos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('checkdate', models.DateTimeField(blank=True, db_column='CheckDate', null=True)),
                ('checknumber', models.CharField(db_column='CheckNumber', max_length=15)),
                ('patientid', models.CharField(db_column='PatientID', max_length=15)),
                ('patientname', models.CharField(blank=True, db_column='PatientName', max_length=25, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=25, null=True)),
                ('age', models.CharField(blank=True, db_column='Age', max_length=25, null=True)),
                ('clinicaldiagnosis', models.CharField(blank=True, db_column='ClinicalDiagnosis', max_length=4000, null=True)),
                ('examinationfindings', models.CharField(blank=True, db_column='ExaminationFindings', max_length=4000, null=True)),
                ('endoscopicdiagnosis', models.CharField(blank=True, db_column='EndoscopicDiagnosis', max_length=4000, null=True)),
                ('pathologicaldiagnosis', models.CharField(blank=True, db_column='PathologicalDiagnosis', max_length=4000, null=True)),
                ('patientreport', models.CharField(blank=True, db_column='PatientReport', max_length=255, null=True)),
                ('hospitalid', models.CharField(blank=True, db_column='HospitalID', max_length=3, null=True)),
            ],
            options={
                'db_table': 'patientbasicinfos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('userid', models.CharField(db_column='UserID', max_length=45)),
                ('departmentid', models.CharField(db_column='DepartmentID', max_length=10)),
                ('hospitalid', models.CharField(db_column='HospitalID', max_length=3)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('age', models.CharField(blank=True, db_column='Age', max_length=4, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
