# Generated by Django 3.2.3 on 2021-06-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
    ]
