# Generated by Django 3.2.3 on 2021-06-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20210627_1655'),
    ]

    operations = [
    ]
